version: "3.8"
services:

    # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database

    # Database Server
    database:
        container_name: database
        image: mariadb:latest
        ports:
            -   3306:3306
        environment:
            MYSQL_DATABASE: blog
            MYSQL_USER: teamweb
            MYSQL_PASSWORD: root@root
            MYSQL_ROOT_PASSWORD: root@root
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: ~